#Running Kruskal-Wallis test and Dunn's test 
##Required packages
```{r}
#loading library 
library(FSA) #version ‘0.9.4’ #dunnTest
library(rstatix) #‘0.7.2’ #rstatix::dunn_test
```

##All genes

```{r - Kruskal-Wallis test (non-parametric)}
original<-read.table(file = "results/tables/gene_count_sd_without_astro_v4.txt", header = T)
original$TYPE<-paste0(original$type,"_",original$gwas_type)

original_per_disease<-split(x = original, f = original$TYPE)

original_AD_J_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$AD_Jansen2019)
original_AD_K_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$AD_Kunkle2019)
original_MS_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$MS_Andlauer2016)
original_ALS_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$ALS_Rheenen2021)
original_PD_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$PD_Nalls2019proxy)
original_SCZ_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$SCZ_Trubetskoy2022)

original_AD_J_k_table<-data.frame(statistic=original_AD_J_k$statistic, parameter=original_AD_J_k$parameter, p.value=original_AD_J_k$p.value, method=original_AD_J_k$method, data.name=original_AD_J_k$data.name, disease="original_AD_J_k")
original_AD_K_k_table<-data.frame(statistic=original_AD_K_k$statistic, parameter=original_AD_K_k$parameter, p.value=original_AD_K_k$p.value, method=original_AD_K_k$method, data.name=original_AD_K_k$data.name, disease="original_AD_K_k")
original_MS_k_table<-data.frame(statistic=original_MS_k$statistic, parameter=original_MS_k$parameter, p.value=original_MS_k$p.value, method=original_MS_k$method, data.name=original_MS_k$data.name, disease="original_MS_k")
original_ALS_k_table<-data.frame(statistic=original_ALS_k$statistic, parameter=original_ALS_k$parameter, p.value=original_ALS_k$p.value, method=original_ALS_k$method, data.name=original_ALS_k$data.name, disease="original_ALS_k")
original_PD_k_table<-data.frame(statistic=original_PD_k$statistic, parameter=original_PD_k$parameter, p.value=original_PD_k$p.value, method=original_PD_k$method, data.name=original_PD_k$data.name, disease="original_PD_k")
original_SCZ_k_table<-data.frame(statistic=original_SCZ_k$statistic, parameter=original_SCZ_k$parameter, p.value=original_SCZ_k$p.value, method=original_SCZ_k$method, data.name=original_SCZ_k$data.name, disease="original_SCZ_k")

Kruskal_Wallis<-rbind(original_AD_J_k_table,original_AD_K_k_table, original_MS_k_table,original_ALS_k_table, original_PD_k_table, original_SCZ_k_table)

write.table(x = Kruskal_Wallis,file = "results/tables/statistical_tests/Kruskal-Wallis_test_without_astro_v6.txt", sep = "\t", quote = F, row.names = F, col.names = T)

```

```{r - Dunn's test (non-paramtric)}
original<-read.table(file = "results/tables/gene_count_sd_without_astro_v4.txt", header = T)
original$TYPE<-paste0(original$type,"_",original$gwas_type)

original_per_disease<-split(x = original, f = original$TYPE)


#analysing the specific samples for stochatic dominance 
original_AD<-rstatix::dunn_test(data = original_per_disease$AD_Jansen2019, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_AD$TYPE<-"AD_Jansen2019"

original_AD_K<-rstatix::dunn_test(data = original_per_disease$AD_Kunkle2019, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_AD_K$TYPE<-"AD_Kunkle2019"

original_MS<-rstatix::dunn_test(data = original_per_disease$MS_Andlauer2016, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_MS$TYPE<-"MS_Andlauer2016"

original_PD<-rstatix::dunn_test(data = original_per_disease$PD_Nalls2019proxy, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_PD$TYPE<-"PD_Nalls2019proxy"

original_ALS<-rstatix::dunn_test(data = original_per_disease$ALS_Rheenen2021, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_ALS$TYPE<-"ALS_Rheenen2021"

original_SCZ<-rstatix::dunn_test(data = original_per_disease$SCZ_Trubetskoy2022, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_SCZ$TYPE<-"SCZ_Trubetskoy2022"

original_dunn<-rbind(original_AD, original_AD_K, original_MS, original_PD, original_ALS, original_SCZ)

write.table(x = original_dunn,file = "results/tables/statistical_tests/gene_count_sd_without_astro_v6_dunn.txt", sep = "\t", quote = F, row.names = F, col.names = T)

original_dunn
```


##INTRONIC,INTERGENIC GENE COUNT 
```{r - Kruskal-Wallis test (non-parametric)}
original<-read.table(file = "results/tables/gene_count_interactome_intronic_sd_without_astro_v4.txt", header = T)
original<-original[!grepl("SCZ_pardinas2018info9_", original$ID),]
original<-original[!grepl("SCZ_trubetskoy2022_", original$ID),]
original_per_disease<-split(x = original, f = original$type)

original_AD_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$AD)
original_MS_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$MS)
original_ALS_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$ALS)
original_PD_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$PD)
original_SCZ_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$SCZ)
```

```{r - Dunn's test (non-paramtric)}
original<-read.table(file = "results/tables/gene_count_interactome_intronic_sd_without_astro_v4.txt", header = T)


original_per_disease<-split(x = original, f = original$type)

#analysing the specific samples for stochatic dominance 
original_AD<-rstatix::dunn_test(data = original_per_disease$AD, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_AD$type<-"AD"

original_MS<-rstatix::dunn_test(data = original_per_disease$MS, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_MS$type<-"MS"

original_PD<-rstatix::dunn_test(data = original_per_disease$PD, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_PD$type<-"PD"

original_ALS<-rstatix::dunn_test(data = original_per_disease$ALS, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_ALS$type<-"ALS"

original_SCZ<-rstatix::dunn_test(data = original_per_disease$SCZ, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_SCZ$type<-"SCZ"

original_dunn<-rbind(original_AD, original_MS, original_PD, original_ALS, original_SCZ, original_long)

write.table(x = original_dunn,file = "results/tables/statistical_tests/gene_count_interactome_intronic_sd_without_astro_v4_dunn.txt", sep = "\t", quote = F, row.names = F, col.names = T)

original_dunn
```


##EXONIC,PROMOTER (WITHOUT ASTROCYTES) GENE COUNT
```{r - Kruskal-Wallis test (non-parametric)}
original<-read.table(file = "results/tables/gene_count_pro_exon_sd_without_astro_v4.txt", header = T)

original_per_disease<-split(x = original, f = original$type)

original_AD_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$AD)
original_MS_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$MS)
original_ALS_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$ALS)
original_PD_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$PD)
original_SCZ_k<-kruskal.test(gene_count ~ cell, data = original_per_disease$SCZ)
```

```{r - Dunn's test (non-paramtric)}
original<-read.table(file = "results/tables/gene_count_pro_exon_sd_without_astro_v4.txt", header = T)
original_per_disease<-split(x = original, f = original$type)

#analysing the specific samples for stochatic dominance 
original_AD<-rstatix::dunn_test(data = original_per_disease$AD, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_AD$type<-"AD"

original_MS<-rstatix::dunn_test(data = original_per_disease$MS, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_MS$type<-"MS"

original_PD<-rstatix::dunn_test(data = original_per_disease$PD, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_PD$type<-"PD"

original_ALS<-rstatix::dunn_test(data = original_per_disease$ALS, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_ALS$type<-"ALS"

original_SCZ<-rstatix::dunn_test(data = original_per_disease$SCZ, formula = gene_count ~ cell, p.adjust.method = "BH", detailed = FALSE)
original_SCZ$type<-"SCZ"

original_dunn<-rbind(original_AD, original_MS, original_PD, original_ALS, original_SCZ)

write.table(x = original_dunn,file = "results/tables/statistical_tests/gene_count_pro_exon_sd_without_astro_v4_dunn.txt", sep = "\t", quote = F, row.names = F, col.names = T)

original_dunn
```
